gpt:
  LLM_API_URL: ${LLM_API_URL}
  LLM_API_TOKEN: ${LLM_API_TOKEN}

game:
  FEED_DELAY: 4
  SALO_DELAY: 8
  MAX_ITEMS: 15
  BASE_PILLS_CHANCE: 0.33
  BASE_PILLS_CHANCE_GROW: 0.75

database_url: "postgres://avrdude@localhost:5432/botdb"
